# Generated by Django 3.0.5 on 2020-08-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipts', models.IntegerField(default=0)),
                ('sells', models.FloatField(default=0)),
                ('receiptsitems', models.IntegerField()),
            ],
        ),
    ]
